import { SPEC, FLOORS, HEIGHT, makeScene, sunPosition } from './model.mjs';
import { OfficeRenderer } from './renderer.mjs';
import { exportGLB } from './export.mjs';
const $=id=>document.getElementById(id);
let office,scene,sectionOpen=false,interiorBeforeSection=false,toastTimer;
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3300);}
function fail(error){console.error(error);$('loading').hidden=true;$('error').hidden=false;$('error-message').textContent=error.message||String(error);$('render-status').textContent='WEBGL UNAVAILABLE';}
function download(data,name,type){const blob=data instanceof Blob?data:new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function chooseFloor(n){office.set('selected',n);$('selection').hidden=!n;document.querySelectorAll('.floor-item').forEach(b=>b.classList.toggle('active',Number(b.dataset.floor)===n));if(!n)return;const f=FLOORS[n-1];$('selected-tag').textContent=`LEVEL ${String(n).padStart(2,'0')} / ${f.y.toFixed(1)} m`;$('selected-use').textContent=f.use;$('selected-area').textContent=`${f.area.toLocaleString()} m²`;$('selected-note').textContent=f.terrace?`พื้นที่ในอาคาร ${f.enclosed} + สวนมีหลังคา ${f.terrace} ตร.ม.`:`ผัง ${f.width} × ${f.depth} ม. · สูงระหว่างชั้น ${f.height} ม.`;}
function updateSun(){const h=Number($('sun-hour').value),d=Number($('sun-season').value),sun=sunPosition(h,d);office.set('hour',h);office.set('day',d);$('sun-time').value=`${String(Math.floor(h)).padStart(2,'0')}:${String(Math.round((h%1)*60)).padStart(2,'0')}`;$('sun-altitude').textContent=`ALT ${sun.altitude.toFixed(0)}°`;$('sun-hour').setAttribute('aria-valuetext',`${$('sun-time').value} นาฬิกา`);}
function updatePresets(name){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('orbit').setAttribute('aria-pressed','false');}
try{
  scene=makeScene();office=new OfficeRenderer($('scene'),scene);
  window.__office14__={renderer:office,get scene(){return scene;},exportGLB:()=>exportGLB(scene),summary:()=>({name:SPEC.name,floors:FLOORS.length,gfa:FLOORS.reduce((s,f)=>s+f.area,0),height:HEIGHT,objects:scene.objects.length,pvPanels:scene.objects.filter(o=>o.name==='PV module 450 W target').length,drawCalls:office.batches.length,webgl:!!office.gl})};
  office.onError=message=>fail(new Error(message));
  office.onPick=chooseFloor;
  office.onInteraction=()=>$('orbit').setAttribute('aria-pressed','false');
  office.onFrame=()=>{const p=office.project([8,FLOORS[9].y+2+9*office.state.explode*2.8,10.5]),label=$('garden-label');const visible=p?.visible&&office.state.cutoff>=10&&Math.cos(office.camera.theta)>.35&&office.state.explode<.1&&window.innerWidth>1100;label.hidden=!visible;if(visible){label.style.left=`${p.x}px`;label.style.top=`${p.y}px`;}$('compass-needle').style.transform=`rotate(${-office.camera.theta*180/Math.PI}deg)`;};
  const list=$('floor-list');
  for(const f of [...FLOORS].reverse()){const b=document.createElement('button');b.className='floor-item';b.dataset.floor=f.level;b.setAttribute('aria-label',`ชั้น ${f.level}, ${f.area} ตารางเมตร, ${f.use}`);b.innerHTML=`<b>${String(f.level).padStart(2,'0')}</b><span>${f.use}${f.terrace?'<small>72 m² covered garden</small>':''}</span><strong>${f.area.toLocaleString()}</strong>`;b.addEventListener('click',()=>{if(office.state.cutoff<f.level){$('cutoff').value=f.level;$('cutoff').dispatchEvent(new Event('input'));}chooseFloor(f.level);});list.append(b);}
  document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(t=>t.setAttribute('aria-selected',String(t===b)));document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==`panel-${b.dataset.tab}`);}));
  document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{office.preset(b.dataset.view);updatePresets(b.dataset.view);}));
  for(const name of ['facade','landscape','interior'])$(name).addEventListener('change',e=>office.set(name,e.target.checked));
  $('finDepth').addEventListener('input',e=>{$('fin-value').value=`${Number(e.target.value).toFixed(2)} m`;});
  $('finDepth').addEventListener('change',e=>{scene=makeScene({finDepth:Number(e.target.value)});office.replaceScene(scene);toast('อัปเดตครีบฟาซาดในโมเดลแล้ว');});
  $('orbit').addEventListener('click',()=>{const on=!office.state.auto;office.set('auto',on);$('orbit').setAttribute('aria-pressed',String(on));});
  $('explode').addEventListener('click',()=>{const on=office.state.explode===0;office.set('explode',on?1:0);$('explode').setAttribute('aria-pressed',String(on));office.preset('hero');updatePresets('hero');toast(on?'แยกชั้นเพื่อดูองค์ประกอบ · ไม่เปลี่ยนขนาดจริง':'กลับสู่ความสูงตามแบบ');});
  $('section').addEventListener('click',()=>{sectionOpen=!sectionOpen;$('section').setAttribute('aria-pressed',String(sectionOpen));$('section-control').hidden=!sectionOpen;if(sectionOpen){interiorBeforeSection=office.state.interior;$('interior').checked=true;office.set('interior',true);$('cutoff').value='8';office.preset('top');updatePresets('top');}else{$('cutoff').value='14';$('interior').checked=interiorBeforeSection;office.set('interior',interiorBeforeSection);office.preset('hero');updatePresets('hero');}$('cutoff').dispatchEvent(new Event('input'));});
  $('cutoff').addEventListener('input',e=>{const n=Number(e.target.value);office.set('cutoff',n);$('cutoff-value').value=`${n} / 14`;if(office.state.selected>n)chooseFloor(0);});
  $('sun-hour').addEventListener('input',updateSun);$('sun-season').addEventListener('change',updateSun);updateSun();
  $('night').addEventListener('click',()=>{const on=!office.state.night;office.set('night',on);$('night').setAttribute('aria-pressed',String(on));$('viewport').classList.toggle('night',on);toast(on?'บรรยากาศกลางคืน · การจัดแสงเพื่อการนำเสนอ':'บรรยากาศกลางวัน');});
  $('clear-selection').addEventListener('click',()=>chooseFloor(0));
  $('reset').addEventListener('click',()=>{sectionOpen=false;for(const [k,v]of Object.entries({cutoff:14,explode:0,facade:true,landscape:true,interior:false,night:false,selected:0,auto:false}))office.set(k,v);for(const n of ['facade','landscape'])$(n).checked=true;$('interior').checked=false;for(const n of ['orbit','explode','section','night'])$(n).setAttribute('aria-pressed','false');$('cutoff').value='14';$('cutoff-value').value='14 / 14';$('section-control').hidden=true;$('viewport').classList.remove('night');$('sun-hour').value='9.5';$('sun-season').value='264';updateSun();$('finDepth').value='.95';$('fin-value').value='0.95 m';scene=makeScene();office.replaceScene(scene);office.preset('hero');chooseFloor(0);updatePresets('hero');});
  $('export').addEventListener('click',async()=>{const button=$('export');button.disabled=true;toast('กำลังสร้าง GLB ครบทั้งอาคาร สำหรับ Blender');try{await new Promise(r=>setTimeout(r,40));const result=exportGLB(scene);download(result,'solstice-14-office-10000sqm.glb','model/gltf-binary');toast('ส่งออกโมเดลครบ 14 ชั้นแล้ว · Blender: File → Import → glTF');}catch(e){toast(`ส่งออกไม่สำเร็จ: ${e.message}`);}finally{button.disabled=false;}});
  $('capture').addEventListener('click',()=>{try{const data=office.screenshot(),a=document.createElement('a');a.href=data;a.download='solstice-14-view.png';a.click();toast('บันทึกภาพจากมุมมองปัจจุบัน');}catch(e){toast(`บันทึกภาพไม่สำเร็จ: ${e.message}`);}});
  if(window.innerWidth<761)document.querySelector('.gestures').textContent='ลาก 1 นิ้วเพื่อหมุน · ใช้ 2 นิ้วเพื่อซูม / เลื่อน';
  office.render();$('render-status').textContent=`WEBGL 2 / ${scene.objects.length.toLocaleString()} ELEMENTS / METRIC`;$('loading').classList.add('done');setTimeout(()=>$('loading').hidden=true,400);
}catch(error){fail(error);}
