import { geometry } from './model.mjs';
/** Portable glTF 2.0 binary exporter; exports the complete design, not a clipped screen state. */
export function exportGLB(scene) {
  const gltf={asset:{version:'2.0',generator:'Solstice 14 / Blender3d'},scene:0,scenes:[{name:scene.spec.name,nodes:[]}],nodes:[],meshes:[],materials:[],accessors:[],bufferViews:[],buffers:[],extras:{units:'metres',coordinateSystem:'X east, Y up, Z south',spec:scene.spec,floors:scene.floors}};
  const chunks=[],materialIndices={},shapeData={},meshIndices={};let byteLength=0;
  function view(array,target){const pad=(4-byteLength%4)%4;if(pad){chunks.push(new Uint8Array(pad));byteLength+=pad;}const index=gltf.bufferViews.length;gltf.bufferViews.push({buffer:0,byteOffset:byteLength,byteLength:array.byteLength,target});chunks.push(new Uint8Array(array.buffer,array.byteOffset,array.byteLength));byteLength+=array.byteLength;return index;}
  function accessor(array,type,componentType,target,extrema=false){const item={bufferView:view(array,target),componentType,count:array.length/(type==='VEC3'?3:1),type};if(extrema){item.min=[Infinity,Infinity,Infinity];item.max=[-Infinity,-Infinity,-Infinity];for(let i=0;i<array.length;i++){let k=i%3;item.min[k]=Math.min(item.min[k],array[i]);item.max[k]=Math.max(item.max[k],array[i]);}}const id=gltf.accessors.length;gltf.accessors.push(item);return id;}
  for(const [name,m]of Object.entries(scene.materials)){materialIndices[name]=gltf.materials.length;gltf.materials.push({name,pbrMetallicRoughness:{baseColorFactor:[...m.color.map(v=>Math.pow(v,2.2)),1],metallicFactor:m.kind===1?.3:m.kind===2?.5:0,roughnessFactor:m.kind===1?.22:m.kind===2?.38:.8},...(m.kind===4?{emissiveFactor:m.color}:{}),doubleSided:false});}
  for(const shape of ['box','sphere','cylinder']){const g=geometry(shape);shapeData[shape]={POSITION:accessor(g.positions,'VEC3',5126,34962,true),NORMAL:accessor(g.normals,'VEC3',5126,34962),indices:accessor(g.indices,'SCALAR',5123,34963)};}
  for(const o of scene.objects){const key=`${o.shape}:${o.material}`;if(!(key in meshIndices)){const g=shapeData[o.shape];meshIndices[key]=gltf.meshes.length;gltf.meshes.push({name:key,primitives:[{attributes:{POSITION:g.POSITION,NORMAL:g.NORMAL},indices:g.indices,material:materialIndices[o.material]}]});}gltf.scenes[0].nodes.push(gltf.nodes.length);gltf.nodes.push({name:o.name,mesh:meshIndices[key],matrix:o.matrix,extras:{floor:o.floor,layer:o.layer,material:o.material}});}
  gltf.buffers=[{byteLength}];const text=new TextEncoder().encode(JSON.stringify(gltf)),jsonLength=(text.length+3)&~3,binLength=(byteLength+3)&~3,total=12+8+jsonLength+8+binLength;
  const out=new Uint8Array(total),dv=new DataView(out.buffer);dv.setUint32(0,0x46546c67,true);dv.setUint32(4,2,true);dv.setUint32(8,total,true);dv.setUint32(12,jsonLength,true);dv.setUint32(16,0x4e4f534a,true);out.fill(32,20,20+jsonLength);out.set(text,20);const binStart=20+jsonLength;dv.setUint32(binStart,binLength,true);dv.setUint32(binStart+4,0x004e4942,true);let offset=binStart+8;for(const c of chunks){out.set(c,offset);offset+=c.length;}return out;
}
